### ISSUE TITLE
Fails to scan (Python 3.5.1)

### ISSUE THREAD

**Issue by FatKiwi** [jekyc/wig#20]
python wig.py anywebsite.domain

results in

Traceback (most recent call last):
  File "wig.py", line 317, in <module>    wig.run()
  File "wig.py", line 244, in run    self.scan_site()
  File "wig.py", line 158, in scan_site    DiscoverMore(self.options, self.data).run()
  File "C:\Users\x\Desktop\wig-0.5.2\classes\discovery.py", line 385, in run    parser = LinkExtractor(strict=False)
File "C:\Users\x\Desktop\wig-0.5.2\classes\discovery.py", line 333, in __init__
    super().__init__(strict=strict)
TypeError: __init__() got an unexpected keyword argument 'strict'

**I tried the 'strict' fix commit to no avail, I'm then getting this:**

Traceback (most recent call last):
  File "wig.py", line 317, in <module>    wig.run()
  File "wig.py", line 244, in run    self.scan_site()
  File "wig.py", line 125, in scan_site    title = DiscoverTitle(self.options, self.data).run() 
_File "C:\Users\x\Desktop\wig-0.5.2\classes\discovery.py", line 769, in run
    self.printer.print_debug_line('Getting title ...', 1)
AttributeError: 'Printer' object has no attribute 'print_debug_line'_

**Comment by jekyc** [comment]
Hi FatKiwi,

I've tested the latest version of wig with python 3.5.1 on Debian, but I can't seem to reproduce the issue you're seeing. I've just tagged a new version (0.6) which includes all commits since 0.5.2. Could you test this version to see if it fixes the issue you're seeing?

**Comment by FatKiwi** [comment]
0.6:
`Traceback (most recent call last):
  File "wig.py", line 382, in <module>
    wig = Wig(args)
  File "wig.py", line 84, in __init__
    'fingerprints': Fingerprints(),
  File "C:\Users\x\Desktop\wig-0.6\classes\fingerprints.py", line 46, in __init__
    self._load_interesting()
  File "C:\Users\x\Desktop\wig-0.6\classes\fingerprints.py", line 106, in _load_interesting
    for fp in fps:
TypeError: 'NoneType' object is not iterable`

**Comment by jekyc** [comment]
Hi FatKiwi,

Thanks for the update - could you please try the latest commit?
I don't have access to a Windows machine, so I've been able to test it on that, but I've changed the way wig builds paths to the json files.

Could you also please check the size and format of your 'data/interesting.json' file? It should be 1967 bytes large.

**Comment by FatKiwi** [comment]
Stunning work mate! The latest commits fixed the issue. Thank you!
