### ISSUE TITLE
Exception handling in discovery.py

### ISSUE THREAD

**Issue by olamotte** [jekyc/wig#7]
Need to check "response" for "NoneType" 

Traceback (most recent call last):
  File "./wig.py", line 318, in <module>
    wig.run()
  File "./wig.py", line 242, in run
    self.scan_site()
  File "./wig.py", line 156, in scan_site
    DiscoverInteresting(self.options, self.data).run()
  File "/home/ubuntu/wig/classes/discovery.py", line 265, in run
    redirected = response.md5_404 in self.error_pages
AttributeError: 'NoneType' object has no attribute 'md5_404'

**Comment by jekyc** [comment]
Hi olamotte,

Thanks for the bug reports. I've committed a fix for the issue - could you please test if this works for you?

**Comment by jekyc** [comment]
This should be fixed in https://github.com/jekyc/wig/pull/9, so I'm closing the issue
